---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:

    - Jellyfin:
        icon: jellyfin.svg
        href: http://192.168.0.23:8096
        ping: http://192.168.0.23:8096

    - Plex:
        icon: plex.svg
        href: http://192.168.0.23:32400/web

    - Jellyserr:
        icon: jellyseerr.svg
        href: http://192.168.0.23:5055

    - Sonarr [ANIME]:
        icon: sonarr.svg
        href: http://192.168.0.23:8990

    - Sonarr [TV]:
        icon: sonarr.svg
        href: http://192.168.0.23:8989 

    - Radarr:
        icon: radarr.svg
        href: http://192.168.0.23:7878

    - Prowlarr:
        icon: prowlarr.svg
        href: http://192.168.0.23:9696

    - qBittorrent:
        icon: qbittorrent.svg
        href: http://192.168.0.23:8080

    - Kavita:
        icon: kavita.svg
        href: http://192.168.0.23:5000

    - Tautulli:
        icon: tautulli.svg
        href: http://192.168.0.23:8181

    - Syncthing:
        icon: syncthing.svg
        href: http://192.168.0.23:8384

- Management:

    - Proxmox [pve1]:
        icon: proxmox.svg
        href: https://192.168.0.73:8006/

    - Proxmox [hoshi]:
        icon: proxmox.svg
        href: https://192.168.0.2:8006/
        description: MS-01

    - Proxmox Backup Server:
        icon: proxmox.svg
        href: https://192.168.0.215:8007/

    - TrueNAS:
        icon: truenas.svg
        href: http://192.168.0.18

    - Beszel:
        icon: beszel.svg
        href: http://192.168.0.11:8090

    - Technitium:
        icon: technitium.png
        href: http://192.168.0.9:5380