---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Media:
    tab: Media
    style: row
    columns: 4

  Management:
    tab: Management
    style: row
    columns: 4